### ISSUE TITLE
margin: auto does not work when used with position: absolute

### ISSUE THREAD

**Issue by yitengjun** [yitengjun/ukiyo-js#3]
```css
img {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  margin: auto;
  width: 80%;
  width: 50%;
}
```
When centering elements, using position: absolute with transform is fine, but using it with margin: auto will cause the parallax element to be misaligned.
